[package]
name = "rsa"
version = "0.1.0"
edition = "2021"
description = "this man is fckn crazy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
num-bigint = "0.4.4"
num-traits = "0.2.18"
rand = "0.8.5"
